import Head from "next/head";
import Navbar from "../../components/Navbar";
import StudentProfile from "../../components/StudentProfile";
import { db } from "../../firebaseConfig";
import {
  collection,
  getDoc,
  getDocs,
  query,
  where,
  doc,
} from "firebase/firestore";

const Student = ({ student }) => {
  return (
    <>
      <Head>
        <title>B2M Library</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo-library.png" />
      </Head>
      <Navbar />
      <div className="bg-white flex flex-wrap md:flex w-full">
        <StudentProfile student={student} />
      </div>
    </>
  );
};

export const getServerSideProps = async (context) => {
  var user;
  const students = [];
  const userDocRef = doc(db, "users", `${context.params.id}`);
  const userDoc = await getDoc(userDocRef);

  if (userDoc.exists()) {
    user = userDoc.data();
  } else {
    console.log("No such document!");
  }

  const studentsCollectionRef = collection(db, "students");

  const queryStudents = query(
    studentsCollectionRef,
    where("email", "==", `${user.email}`),
    where("password", "==", `${user.password}`)
  );

  const studentData = await getDocs(queryStudents);

  studentData.docs.map((doc) => {
    students.push({
      ...doc.data(),
      id: doc.id,
    });
  });

  const currentStudent = students.find(
    (student) =>
      student.email === user.email && student.password === user.password
  );

  return {
    props: {
      student: currentStudent,
    },
  };
};

export default Student;
